// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260918101222_AddNavigationProperties")]
    partial class AddNavigationProperties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Backend.Models.Event.Concert", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BandId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConcertID")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Organizer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("BandId");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("Concert");
                });

            modelBuilder.Entity("Backend.Models.Event.Event", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("EntryTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("PriceType")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartDay")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ValidLocationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("MemberId");

                    b.HasIndex("ValidLocationId");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("Backend.Models.Event.Festival", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndDay")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FestivalID")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FestivalNameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Organizer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("FestivalNameId", "EndDate")
                        .IsUnique();

                    b.ToTable("Festival");
                });

            modelBuilder.Entity("Backend.Models.Event.FestivalName", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Festival_NameID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FestivalName");
                });

            modelBuilder.Entity("Backend.Models.Event.Party", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndDay")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Organizer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PartyID")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PartyNameId")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("PartyNameId", "EndDate")
                        .IsUnique();

                    b.ToTable("Party");
                });

            modelBuilder.Entity("Backend.Models.Event.PartyName", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Party_NameID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Guid");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Partyname");
                });

            modelBuilder.Entity("Backend.Models.Location.City", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Backend.Models.Location.District", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DistrictID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("District");
                });

            modelBuilder.Entity("Backend.Models.Location.EventLocation", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Event_LocationID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EventLocation");
                });

            modelBuilder.Entity("Backend.Models.Location.Region", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RegionID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Guid");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Region");
                });

            modelBuilder.Entity("Backend.Models.Location.State", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StateID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Guid");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("State");
                });

            modelBuilder.Entity("Backend.Models.Location.ValidLocation", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventLocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ValidLocationID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Guid");

                    b.HasIndex("DistrictId");

                    b.HasIndex("EventLocationId");

                    b.HasIndex("RegionId");

                    b.HasIndex("StateId");

                    b.HasIndex("CityId", "DistrictId", "RegionId", "StateId", "EventLocationId")
                        .IsUnique();

                    b.ToTable("ValidLocation");
                });

            modelBuilder.Entity("Backend.Models.Member.Member", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("Nickname")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Member");
                });

            modelBuilder.Entity("Backend.Models.Music.Band", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BandID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Band");
                });

            modelBuilder.Entity("Backend.Models.Music.Instrument", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("InstrumentID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Instrument");
                });

            modelBuilder.Entity("Backend.Models.Music.MusicGenre", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MusicGenreID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Guid");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.ToTable("MusicGenre");
                });

            modelBuilder.Entity("Backend.Models.Music.Musician", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MusicianID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Guid");

                    b.HasIndex("ArtistName")
                        .IsUnique();

                    b.HasIndex("FirstName", "LastName")
                        .IsUnique();

                    b.ToTable("Musician");
                });

            modelBuilder.Entity("Backend.Models.Music.Song", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SongID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Guid");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Song");
                });

            modelBuilder.Entity("Backend.Models.Relations.BandMusicGenre", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BandId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MusicGenreId")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("MusicGenreId");

                    b.HasIndex("BandId", "MusicGenreId")
                        .IsUnique();

                    b.ToTable("BandMusicGenre");
                });

            modelBuilder.Entity("Backend.Models.Relations.BandMusician", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BandId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MusicianId")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("MusicianId");

                    b.HasIndex("BandId", "MusicianId")
                        .IsUnique();

                    b.ToTable("BandMusician");
                });

            modelBuilder.Entity("Backend.Models.Relations.BandSong", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BandId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SongId")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("SongId");

                    b.HasIndex("BandId", "SongId")
                        .IsUnique();

                    b.ToTable("BandSong");
                });

            modelBuilder.Entity("Backend.Models.Relations.ConcertBand", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BandId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConcertId")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("BandId");

                    b.HasIndex("ConcertId", "BandId")
                        .IsUnique();

                    b.ToTable("ConcertBand");
                });

            modelBuilder.Entity("Backend.Models.Relations.FestivalBand", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BandId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Day")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FestivalId")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("BandId");

                    b.HasIndex("FestivalId", "BandId")
                        .IsUnique();

                    b.ToTable("FestivalBand");
                });

            modelBuilder.Entity("Backend.Models.Relations.MusicianInstrument", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MusicianId")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("MusicianId", "InstrumentId")
                        .IsUnique();

                    b.ToTable("MusicianInstrument");
                });

            modelBuilder.Entity("Backend.Models.Relations.PartyBand", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BandId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("BandId");

                    b.HasIndex("PartyId", "BandId")
                        .IsUnique();

                    b.ToTable("PartyBand");
                });

            modelBuilder.Entity("Backend.Models.Event.Concert", b =>
                {
                    b.HasOne("Backend.Models.Music.Band", "Band")
                        .WithMany()
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Event.Event", "Event")
                        .WithOne("Concert")
                        .HasForeignKey("Backend.Models.Event.Concert", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Band");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Backend.Models.Event.Event", b =>
                {
                    b.HasOne("Backend.Models.Member.Member", "Member")
                        .WithMany("OrganizedEvents")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Location.ValidLocation", "ValidLocation")
                        .WithMany()
                        .HasForeignKey("ValidLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("ValidLocation");
                });

            modelBuilder.Entity("Backend.Models.Event.Festival", b =>
                {
                    b.HasOne("Backend.Models.Event.Event", "Event")
                        .WithOne("Festival")
                        .HasForeignKey("Backend.Models.Event.Festival", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Event.FestivalName", "FestivalName")
                        .WithMany()
                        .HasForeignKey("FestivalNameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("FestivalName");
                });

            modelBuilder.Entity("Backend.Models.Event.Party", b =>
                {
                    b.HasOne("Backend.Models.Event.Event", "Event")
                        .WithOne("Party")
                        .HasForeignKey("Backend.Models.Event.Party", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Event.PartyName", "PartyName")
                        .WithMany()
                        .HasForeignKey("PartyNameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("PartyName");
                });

            modelBuilder.Entity("Backend.Models.Location.ValidLocation", b =>
                {
                    b.HasOne("Backend.Models.Location.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Location.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Location.EventLocation", "EventLocation")
                        .WithMany()
                        .HasForeignKey("EventLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Location.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Location.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("District");

                    b.Navigation("EventLocation");

                    b.Navigation("Region");

                    b.Navigation("State");
                });

            modelBuilder.Entity("Backend.Models.Relations.BandMusicGenre", b =>
                {
                    b.HasOne("Backend.Models.Music.Band", "Band")
                        .WithMany("MusicGenres")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Music.MusicGenre", "MusicGenre")
                        .WithMany("Bands")
                        .HasForeignKey("MusicGenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Band");

                    b.Navigation("MusicGenre");
                });

            modelBuilder.Entity("Backend.Models.Relations.BandMusician", b =>
                {
                    b.HasOne("Backend.Models.Music.Band", "Band")
                        .WithMany("Musicians")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Music.Musician", "Musician")
                        .WithMany("Bands")
                        .HasForeignKey("MusicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Band");

                    b.Navigation("Musician");
                });

            modelBuilder.Entity("Backend.Models.Relations.BandSong", b =>
                {
                    b.HasOne("Backend.Models.Music.Band", "Band")
                        .WithMany("Songs")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Music.Song", "Song")
                        .WithMany("Bands")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Band");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Backend.Models.Relations.ConcertBand", b =>
                {
                    b.HasOne("Backend.Models.Music.Band", "Band")
                        .WithMany("Concerts")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Event.Concert", "Concert")
                        .WithMany("Bands")
                        .HasForeignKey("ConcertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Band");

                    b.Navigation("Concert");
                });

            modelBuilder.Entity("Backend.Models.Relations.FestivalBand", b =>
                {
                    b.HasOne("Backend.Models.Music.Band", "Band")
                        .WithMany("Festivals")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Event.Festival", "Festival")
                        .WithMany("Bands")
                        .HasForeignKey("FestivalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Band");

                    b.Navigation("Festival");
                });

            modelBuilder.Entity("Backend.Models.Relations.MusicianInstrument", b =>
                {
                    b.HasOne("Backend.Models.Music.Instrument", "Instrument")
                        .WithMany("Musicians")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Music.Musician", "Musician")
                        .WithMany("Instruments")
                        .HasForeignKey("MusicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");

                    b.Navigation("Musician");
                });

            modelBuilder.Entity("Backend.Models.Relations.PartyBand", b =>
                {
                    b.HasOne("Backend.Models.Music.Band", "Band")
                        .WithMany("Parties")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Event.Party", "Party")
                        .WithMany("Bands")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Band");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("Backend.Models.Event.Concert", b =>
                {
                    b.Navigation("Bands");
                });

            modelBuilder.Entity("Backend.Models.Event.Event", b =>
                {
                    b.Navigation("Concert");

                    b.Navigation("Festival");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("Backend.Models.Event.Festival", b =>
                {
                    b.Navigation("Bands");
                });

            modelBuilder.Entity("Backend.Models.Event.Party", b =>
                {
                    b.Navigation("Bands");
                });

            modelBuilder.Entity("Backend.Models.Member.Member", b =>
                {
                    b.Navigation("OrganizedEvents");
                });

            modelBuilder.Entity("Backend.Models.Music.Band", b =>
                {
                    b.Navigation("Concerts");

                    b.Navigation("Festivals");

                    b.Navigation("MusicGenres");

                    b.Navigation("Musicians");

                    b.Navigation("Parties");

                    b.Navigation("Songs");
                });

            modelBuilder.Entity("Backend.Models.Music.Instrument", b =>
                {
                    b.Navigation("Musicians");
                });

            modelBuilder.Entity("Backend.Models.Music.MusicGenre", b =>
                {
                    b.Navigation("Bands");
                });

            modelBuilder.Entity("Backend.Models.Music.Musician", b =>
                {
                    b.Navigation("Bands");

                    b.Navigation("Instruments");
                });

            modelBuilder.Entity("Backend.Models.Music.Song", b =>
                {
                    b.Navigation("Bands");
                });
#pragma warning restore 612, 618
        }
    }
}
