// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Backend.Models.Event.Event", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AgeRestriction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventID")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("ExtraInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Facebook")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instagram")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OrganizerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TikTok")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("MemberId");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("Backend.Models.Event.EventDate", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DoorsOpen")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("End")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Presale")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Price")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketUrl")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ValidLocationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("ValidLocationId");

                    b.HasIndex("EventId", "Position")
                        .IsUnique();

                    b.ToTable("EventDate");
                });

            modelBuilder.Entity("Backend.Models.Event.Organizer", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrganizerID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Organizer");
                });

            modelBuilder.Entity("Backend.Models.Location.City", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Backend.Models.Location.District", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DistrictID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("District");
                });

            modelBuilder.Entity("Backend.Models.Location.EventLocation", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Event_LocationID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EventLocation");
                });

            modelBuilder.Entity("Backend.Models.Location.Region", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RegionID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Guid");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Region");
                });

            modelBuilder.Entity("Backend.Models.Location.State", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StateID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Guid");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("State");
                });

            modelBuilder.Entity("Backend.Models.Location.ValidLocation", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DistrictId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EventLocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HouseNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .HasColumnType("TEXT");

                    b.Property<int>("ValidLocationID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Guid");

                    b.HasIndex("CityId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("EventLocationId");

                    b.HasIndex("RegionId");

                    b.HasIndex("StateId");

                    b.ToTable("ValidLocation");
                });

            modelBuilder.Entity("Backend.Models.Member.Member", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("Nickname")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Member");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("00000000-0000-0000-0000-000000000001"),
                            Birthday = new DateOnly(2000, 1, 1),
                            EMail = "dev@example.com",
                            FirstName = "Test",
                            Gender = "divers",
                            HouseNumber = "1",
                            LastName = "Mitglied",
                            Location = "Teststadt",
                            MemberID = 1,
                            Nickname = "Dev",
                            Password = "dev",
                            PhoneNumber = "0000000000",
                            PostalCode = "00000",
                            Role = 0,
                            Street = "Teststraße",
                            Username = "dev"
                        });
                });

            modelBuilder.Entity("Backend.Models.Music.Band", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BandID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Band");
                });

            modelBuilder.Entity("Backend.Models.Music.Instrument", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("InstrumentID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Instrument");
                });

            modelBuilder.Entity("Backend.Models.Music.MusicGenre", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MusicGenreID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Guid");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.ToTable("MusicGenre");
                });

            modelBuilder.Entity("Backend.Models.Music.Musician", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<int>("MusicianID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Guid");

                    b.HasIndex("ArtistName")
                        .IsUnique();

                    b.ToTable("Musician");
                });

            modelBuilder.Entity("Backend.Models.Music.Song", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SongID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Guid");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Song");
                });

            modelBuilder.Entity("Backend.Models.Relations.BandMusicGenre", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BandId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MusicGenreId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("Guid");

                    b.HasIndex("MusicGenreId");

                    b.HasIndex("BandId", "MusicGenreId")
                        .IsUnique();

                    b.ToTable("BandMusicGenre");
                });

            modelBuilder.Entity("Backend.Models.Relations.BandMusician", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BandId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MusicianId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("Guid");

                    b.HasIndex("MusicianId");

                    b.HasIndex("BandId", "MusicianId")
                        .IsUnique();

                    b.ToTable("BandMusician");
                });

            modelBuilder.Entity("Backend.Models.Relations.BandSong", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BandId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SongId")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("SongId");

                    b.HasIndex("BandId", "SongId")
                        .IsUnique();

                    b.ToTable("BandSong");
                });

            modelBuilder.Entity("Backend.Models.Relations.EventArtist", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BandId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Performance")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("Guid");

                    b.HasIndex("BandId");

                    b.HasIndex("EventId", "BandId")
                        .IsUnique();

                    b.ToTable("EventArtist");
                });

            modelBuilder.Entity("Backend.Models.Relations.MusicianInstrument", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MusicianId")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("MusicianId", "InstrumentId")
                        .IsUnique();

                    b.ToTable("MusicianInstrument");
                });

            modelBuilder.Entity("Backend.Models.Event.Event", b =>
                {
                    b.HasOne("Backend.Models.Member.Member", "Member")
                        .WithMany("OrganizedEvents")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Event.Organizer", "Organizer")
                        .WithMany()
                        .HasForeignKey("OrganizerId");

                    b.Navigation("Member");

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("Backend.Models.Event.EventDate", b =>
                {
                    b.HasOne("Backend.Models.Event.Event", "Event")
                        .WithMany("Dates")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Location.ValidLocation", "ValidLocation")
                        .WithMany()
                        .HasForeignKey("ValidLocationId");

                    b.Navigation("Event");

                    b.Navigation("ValidLocation");
                });

            modelBuilder.Entity("Backend.Models.Location.ValidLocation", b =>
                {
                    b.HasOne("Backend.Models.Location.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.HasOne("Backend.Models.Location.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId");

                    b.HasOne("Backend.Models.Location.EventLocation", "EventLocation")
                        .WithMany()
                        .HasForeignKey("EventLocationId");

                    b.HasOne("Backend.Models.Location.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId");

                    b.HasOne("Backend.Models.Location.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId");

                    b.Navigation("City");

                    b.Navigation("District");

                    b.Navigation("EventLocation");

                    b.Navigation("Region");

                    b.Navigation("State");
                });

            modelBuilder.Entity("Backend.Models.Relations.BandMusicGenre", b =>
                {
                    b.HasOne("Backend.Models.Music.Band", "Band")
                        .WithMany("MusicGenres")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Music.MusicGenre", "MusicGenre")
                        .WithMany("Bands")
                        .HasForeignKey("MusicGenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Band");

                    b.Navigation("MusicGenre");
                });

            modelBuilder.Entity("Backend.Models.Relations.BandMusician", b =>
                {
                    b.HasOne("Backend.Models.Music.Band", "Band")
                        .WithMany("Musicians")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Music.Musician", "Musician")
                        .WithMany("Bands")
                        .HasForeignKey("MusicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Band");

                    b.Navigation("Musician");
                });

            modelBuilder.Entity("Backend.Models.Relations.BandSong", b =>
                {
                    b.HasOne("Backend.Models.Music.Band", "Band")
                        .WithMany("Songs")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Music.Song", "Song")
                        .WithMany("Bands")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Band");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Backend.Models.Relations.EventArtist", b =>
                {
                    b.HasOne("Backend.Models.Music.Band", "Band")
                        .WithMany("Events")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Event.Event", "Event")
                        .WithMany("Artists")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Band");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Backend.Models.Relations.MusicianInstrument", b =>
                {
                    b.HasOne("Backend.Models.Music.Instrument", "Instrument")
                        .WithMany("Musicians")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Music.Musician", "Musician")
                        .WithMany("Instruments")
                        .HasForeignKey("MusicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");

                    b.Navigation("Musician");
                });

            modelBuilder.Entity("Backend.Models.Event.Event", b =>
                {
                    b.Navigation("Artists");

                    b.Navigation("Dates");
                });

            modelBuilder.Entity("Backend.Models.Member.Member", b =>
                {
                    b.Navigation("OrganizedEvents");
                });

            modelBuilder.Entity("Backend.Models.Music.Band", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("MusicGenres");

                    b.Navigation("Musicians");

                    b.Navigation("Songs");
                });

            modelBuilder.Entity("Backend.Models.Music.Instrument", b =>
                {
                    b.Navigation("Musicians");
                });

            modelBuilder.Entity("Backend.Models.Music.MusicGenre", b =>
                {
                    b.Navigation("Bands");
                });

            modelBuilder.Entity("Backend.Models.Music.Musician", b =>
                {
                    b.Navigation("Bands");

                    b.Navigation("Instruments");
                });

            modelBuilder.Entity("Backend.Models.Music.Song", b =>
                {
                    b.Navigation("Bands");
                });
#pragma warning restore 612, 618
        }
    }
}
